#!/usr/bin/env perl
#
# my dotfiles!  (exciting stuff man)
#
# main install
# currently installs prezto
#
# I use system all over the place, trying to avoid many (hopfully all)
# perl module dependencies.
#

use strict;
use warnings;
use Data::Dumper;
use File::Basename;
use feature "switch";
use File::Path qw(remove_tree);
use YAML::Any;

main();

sub main
{
    copyProjectDir();
    runInstall( getConfig() );
}

# load our configuration
#
# C is a copy (automatically recursively copy directories)
# @ is symlink
sub getConfig
{
    my $HOME    = $ENV{HOME};
    my $BASEDIR = dirname(__FILE__);

    my $conf_file = loadConf();

    # Add directories
    $conf_file =~ s/__HOME__/$HOME/g;
    $conf_file =~ s/__BASEDIR__/$BASEDIR/g;

    my $ret_struct = Load($conf_file);

    return eval{$ret_struct;}
}

#
# This routine handles ensuring that the main project directory is copied to
# $HOME/.dotfiles  Makes sure we're already in that directory first.
#
sub copyProjectDir
{
    my $HOME    = $ENV{HOME};
    my $BASEDIR = dirname(__FILE__);
    my $dotdir  = $ENV{HOME} . "/.dotfiles";

    # If the directory already exists, we don't need to do anything
    return unless ( !-d $dotdir );

    # Use the runinstall function to do the copy and setup
    runInstall( { rules => [ { action => 'copy', file => "$BASEDIR", target => "$HOME/.dotfiles" } ] } );

    system("cd $dotdir;git submodule update --init --recursive");
}

# Runs through the ruleset
sub runInstall
{
    my ($config) = @_;

    foreach my $rule ( @{ $config->{rules} } )
    {
        # If the target exists and is a plain file
        if ( -l $rule->{target} or -f $rule->{target} )
        {
            unlink( $rule->{target} );
        }
        elsif ( -d $rule->{target} )    # if the target exists and is a directory
        {
            # try to protect folks from doing something dumb
            die "NOT DELETING YOUR HOME DIRECTORY" if ( $rule->{target} eq $ENV{'HOME'} );

            remove_tree( $rule->{target} );

        }

        given ( $rule->{action} )
        {
            when ("copy")    { system "cp -r " . $rule->{file} . " " . $rule->{target} . "\n" }
            when ("symlink") { system "ln -s " . $rule->{file} . " " . $rule->{target} . "\n" }
        }
    }
}

#
# Loads the config file, slurps it into a variable, returns it.
#
sub loadConf
{
    my $fh;
    my $ret_string;
    my $BASEDIR=dirname(__FILE__);

    open($fh, "<", "$BASEDIR/dotfiles.conf") || die "Couldn't open $BASEDIR/dotfiles.conf:$!";
    while(<$fh>)
    {
        $ret_string .= $_;
    }

    return $ret_string;
}
